//
// Generated by Microsoft (R) D3DX9 Shader Compiler 5.04.00.2904
//
//   fxc /T ps_1_4 /Fc wynik_asemblera.asm
//    C:\Program Files (x86)\Steam\steamapps\common\Clickteam Fusion 2.5\Effects\Foxioo Shader Pack\Coloristic\Other\Inverted\Brightness\Invert Brightness (Switch) [Legacy].fx
//
//
// Parameters:
//
//   sampler2D S2D_Background;
//   sampler2D S2D_Image;
//   bool _Blending_Mode;
//   float _Mixing;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   _Mixing        c0       1
//   _Blending_Mode c1       1
//   S2D_Image      s0       1
//   S2D_Background s1       1
//

    ps_1_4
    def c2, 1, 1, 1, -1
    def c3, 0, 0, 0, 1
    texld r0, t0
    texld r1, t0
    add r2.x, r0.z, -r0.x
    add r3.y, r0.x, -r0.y
    add r4.z, r0.y, -r0.z
    add r2.x, r0.y, r2.x
    add r2.y, r0.z, r3.y
    add r2.z, r0.x, r4.z
    mov r3.x, r0.w
    phase
    mov r3.w, r3.x
    mul r4.w, c1.x, c2.w
  + add r2.xyz, -r2, c2
    mul r5.w, c0.x, c2.w
  + cmp r0.xyz, r4.w, r0, r1
    add r1.w, r5.w, c3.w
    mul r0.xyz, r0, r1.w
  + mov r0.w, r3.w
    mad r0.xyz, r2, c0.x, r0

// approximately 15 instruction slots used (2 texture, 13 arithmetic)
